[package]
name = "runtime-state"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
runtime-primitives = { workspace = true }
runtime-object = { workspace = true }
runtime-scheduler = { workspace = true }
runtime-network = { workspace = true }
