# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tibios/primitives/v1/identity.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tibios/primitives/v1/identity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#tibios/primitives/v1/identity.proto\x12\x14tibios.primitives.v1\"\x19\n\x08ObjectId\x12\r\n\x05value\x18\x01 \x01(\t\"\x1e\n\rObjectVersion\x12\r\n\x05value\x18\x01 \x01(\t\"\x1c\n\x0b\x43ontentHash\x12\r\n\x05value\x18\x01 \x01(\t\"\x1b\n\nWorkloadId\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\x0c\x41llocationId\x12\r\n\x05value\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tibios.primitives.v1.identity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECTID']._serialized_start=61
  _globals['_OBJECTID']._serialized_end=86
  _globals['_OBJECTVERSION']._serialized_start=88
  _globals['_OBJECTVERSION']._serialized_end=118
  _globals['_CONTENTHASH']._serialized_start=120
  _globals['_CONTENTHASH']._serialized_end=148
  _globals['_WORKLOADID']._serialized_start=150
  _globals['_WORKLOADID']._serialized_end=177
  _globals['_ALLOCATIONID']._serialized_start=179
  _globals['_ALLOCATIONID']._serialized_end=208
# @@protoc_insertion_point(module_scope)
