# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tibios_ray.transport._generated.tibios.worker.v1 import worker_pb2 as tibios_dot_worker_dot_v1_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tibios/worker/v1/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerExecutionStub:
    """WorkerExecution — the Worker Contract's gRPC surface. Exactly three
    RPCs, permanently: SubmitJob, Cancel, Pulse. No fourth RPC exists; the
    ExecutionReport rides the SubmitJob response stream rather than a
    separate RPC (design.md D4).
    docs/architecture/18-worker-model.md — the Worker Contract.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_stream(
                '/tibios.worker.v1.WorkerExecution/SubmitJob',
                request_serializer=tibios_dot_worker_dot_v1_dot_worker__pb2.ExecutionContext.SerializeToString,
                response_deserializer=tibios_dot_worker_dot_v1_dot_worker__pb2.ExecutionResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/tibios.worker.v1.WorkerExecution/Cancel',
                request_serializer=tibios_dot_worker_dot_v1_dot_worker__pb2.CancelRequest.SerializeToString,
                response_deserializer=tibios_dot_worker_dot_v1_dot_worker__pb2.CancelAck.FromString,
                _registered_method=True)
        self.Pulse = channel.unary_unary(
                '/tibios.worker.v1.WorkerExecution/Pulse',
                request_serializer=tibios_dot_worker_dot_v1_dot_worker__pb2.PulseRequest.SerializeToString,
                response_deserializer=tibios_dot_worker_dot_v1_dot_worker__pb2.ExecutionPulse.FromString,
                _registered_method=True)


class WorkerExecutionServicer:
    """WorkerExecution — the Worker Contract's gRPC surface. Exactly three
    RPCs, permanently: SubmitJob, Cancel, Pulse. No fourth RPC exists; the
    ExecutionReport rides the SubmitJob response stream rather than a
    separate RPC (design.md D4).
    docs/architecture/18-worker-model.md — the Worker Contract.
    """

    def SubmitJob(self, request, context):
        """SubmitJob — starts one execution. The response stream carries
        ExecutionEvent messages followed by exactly one terminal
        ExecutionReport, always last.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Cancel — cooperatively requests cancellation of one in-flight
        execution, correlated by WorkloadId. Returns CancelAck: accepted,
        not terminated.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pulse(self, request, context):
        """Pulse — a Runtime-pulled health check for one in-flight execution,
        correlated by WorkloadId.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerExecutionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_stream_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=tibios_dot_worker_dot_v1_dot_worker__pb2.ExecutionContext.FromString,
                    response_serializer=tibios_dot_worker_dot_v1_dot_worker__pb2.ExecutionResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=tibios_dot_worker_dot_v1_dot_worker__pb2.CancelRequest.FromString,
                    response_serializer=tibios_dot_worker_dot_v1_dot_worker__pb2.CancelAck.SerializeToString,
            ),
            'Pulse': grpc.unary_unary_rpc_method_handler(
                    servicer.Pulse,
                    request_deserializer=tibios_dot_worker_dot_v1_dot_worker__pb2.PulseRequest.FromString,
                    response_serializer=tibios_dot_worker_dot_v1_dot_worker__pb2.ExecutionPulse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tibios.worker.v1.WorkerExecution', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tibios.worker.v1.WorkerExecution', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerExecution:
    """WorkerExecution — the Worker Contract's gRPC surface. Exactly three
    RPCs, permanently: SubmitJob, Cancel, Pulse. No fourth RPC exists; the
    ExecutionReport rides the SubmitJob response stream rather than a
    separate RPC (design.md D4).
    docs/architecture/18-worker-model.md — the Worker Contract.
    """

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tibios.worker.v1.WorkerExecution/SubmitJob',
            tibios_dot_worker_dot_v1_dot_worker__pb2.ExecutionContext.SerializeToString,
            tibios_dot_worker_dot_v1_dot_worker__pb2.ExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tibios.worker.v1.WorkerExecution/Cancel',
            tibios_dot_worker_dot_v1_dot_worker__pb2.CancelRequest.SerializeToString,
            tibios_dot_worker_dot_v1_dot_worker__pb2.CancelAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pulse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tibios.worker.v1.WorkerExecution/Pulse',
            tibios_dot_worker_dot_v1_dot_worker__pb2.PulseRequest.SerializeToString,
            tibios_dot_worker_dot_v1_dot_worker__pb2.ExecutionPulse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
