//! Tier 3 (design.md D12): four `#[ignore]`d end-to-end tests driving a real
//! GGUF model through `LocalInferWorker` and the real `MpscExecutionChannel`
//! (via `generous_channel`), unmodified — the success criterion is "streams
//! real tokens end-to-end through the existing O1-O4 harness". `#[ignore]`
//! means `cargo test -p runtime --features llamacpp` never runs any of
//! these by default (`local-infer-llamacpp-engine/spec.md` — "Real-Engine
//! Tests Are Ignored By Default"). Run explicitly with:
//!
//! ```text
//! TIBIOS_LOCAL_INFER_MODEL_PATH=/abs/path/model.gguf \
//!     cargo test -p runtime --features llamacpp -- --ignored
//! ```
//!
//! A sibling of `engine/`, not a child: these need `#[tokio::test]`, which
//! the engine subtree's async-free scans forbid (design.md D12).

use std::collections::BTreeMap;
use std::sync::Arc;
use std::time::Duration;

use runtime_allocation::AllocationContract;
use runtime_primitives::WorkloadId;
use runtime_worker::{
    CancelAck, EndOfStream, ExecutionEvent, ExecutionPhase, MetricsSnapshot, OutputChunk,
    WorkerService,
};

use super::super::conformance::{context_with, generous_channel};
use super::{build_local_infer_worker, LocalInferWorker};

/// Fails fast, before any FFI call, when the operator hasn't supplied a
/// model — a harness-misconfiguration report, not a product panic
/// (design.md D12). Deliberately a panic, not the `proto_drift.rs` skip
/// pattern: `--ignored` is an explicit opt-in, so a silent pass would let
/// this change's one manual verification procedure rot unnoticed.
///
/// The message deliberately does not repeat the full invocation (the
/// module doc comment above already has it, in a fenced code block the
/// containment scan exempts as a comment): reaching this panic requires
/// having already run with the feature enabled, and spelling the feature
/// name out here, in code rather than in a comment, would itself violate
/// `engine_names_stay_inside_the_engine_module`'s containment invariant
/// (`local-infer-llamacpp-engine/spec.md` — "The llama.cpp Name Stays
/// Inside The Engine Module").
fn required_model_path() -> String {
    std::env::var("TIBIOS_LOCAL_INFER_MODEL_PATH").unwrap_or_else(|_| {
        panic!(
            "these tests require an operator-supplied GGUF model. Set \
             TIBIOS_LOCAL_INFER_MODEL_PATH=/abs/path/model.gguf and re-run with \
             `-- --ignored` (see this file's module doc comment for the full \
             invocation)"
        )
    })
}

fn execution_parameters(prompt: &str, max_tokens: &str) -> BTreeMap<String, String> {
    let mut execution_parameters = BTreeMap::new();
    execution_parameters.insert("prompt".to_string(), prompt.to_string());
    execution_parameters.insert("max_tokens".to_string(), max_tokens.to_string());
    execution_parameters
}

#[tokio::test(flavor = "multi_thread")]
#[ignore]
async fn a_real_model_streams_tokens_end_to_end() {
    let _model = required_model_path();
    let worker = build_local_infer_worker();
    let workload_id = WorkloadId::new();
    let (channel, mut receiver) = generous_channel();
    let context = context_with(
        workload_id,
        AllocationContract::new(Duration::from_secs(120)),
        execution_parameters("Once upon a time,", "8"),
    );

    let report = worker
        .execute(context, channel)
        .await
        .expect("execute must complete successfully against a real model");
    assert_eq!(report.final_phase, ExecutionPhase::Completed);

    let mut events = Vec::new();
    while let Ok(event) = receiver.try_recv() {
        events.push(event);
    }

    let mut bytes = Vec::new();
    let mut sequences = Vec::new();
    for event in &events {
        if let ExecutionEvent::OutputChunk(OutputChunk { data, sequence }) = event {
            sequences.push(*sequence);
            bytes.extend_from_slice(data);
        }
    }
    let n = sequences.len() as u64;
    assert!((1..=8).contains(&n), "expected 1..=8 tokens, got {n}");
    assert_eq!(
        sequences,
        (0..n).collect::<Vec<u64>>(),
        "OutputChunk sequences must be contiguous, starting at 0"
    );

    let tokens_produced = events.iter().find_map(|event| match event {
        ExecutionEvent::MetricsSnapshot(MetricsSnapshot { metrics }) => {
            metrics.get("tokens_produced").copied()
        }
        _ => None,
    });
    assert_eq!(
        tokens_produced,
        Some(n as f64),
        "MetricsSnapshot[\"tokens_produced\"] must equal the OutputChunk count"
    );

    assert!(
        matches!(events.last(), Some(ExecutionEvent::EndOfStream(EndOfStream))),
        "EndOfStream must be the last event"
    );

    let text = String::from_utf8(bytes).expect("generated bytes must be valid UTF-8");
    assert!(!text.is_empty(), "generated text must be non-empty");
}

#[tokio::test(flavor = "multi_thread")]
#[ignore]
async fn cancelling_a_real_decode_loop_stops_well_before_max_tokens() {
    let _model = required_model_path();
    // `Arc`-wrapped so a clone can be moved into the spawned task (needed to
    // actually drive the blocking decode loop) while this scope keeps its
    // own handle to call `cancel` on (mirrors `local_infer/mod.rs`'s
    // existing abandonment test's deterministic-timing approach).
    let worker = Arc::new(build_local_infer_worker());
    let worker_for_task = Arc::clone(&worker);
    let workload_id = WorkloadId::new();
    let (channel, mut receiver) = generous_channel();
    let context = context_with(
        workload_id,
        AllocationContract::new(Duration::from_secs(120)),
        execution_parameters("Once upon a time,", "512"),
    );

    let execute_handle =
        tokio::spawn(async move { worker_for_task.execute(context, channel).await });

    let mut output_chunks = 0usize;
    loop {
        match receiver
            .recv()
            .await
            .expect("execution must emit at least one OutputChunk before cancellation")
        {
            ExecutionEvent::OutputChunk(_) => {
                output_chunks += 1;
                break;
            }
            _ => continue,
        }
    }

    let cancel_result = worker.cancel(workload_id).await;
    assert_eq!(cancel_result, Ok(CancelAck));

    let report = execute_handle
        .await
        .expect("execute task must not panic")
        .expect("a cancelled execution still returns a report, not an error");
    assert_eq!(report.final_phase, ExecutionPhase::Cancelled);

    while let Some(event) = receiver.recv().await {
        if matches!(event, ExecutionEvent::OutputChunk(_)) {
            output_chunks += 1;
        }
    }
    // Deliberately not "exactly one more token": the cancel lands at a
    // scheduling-dependent index. The bounded claim matches
    // `generous_channel`'s own capacity (design.md D12).
    assert!(
        output_chunks < 32,
        "cancellation must stop well before the 512-token max, got {output_chunks} chunks"
    );
}

#[tokio::test(flavor = "multi_thread")]
#[ignore]
async fn two_identical_requests_produce_identical_bytes() {
    let _model = required_model_path();
    let worker = build_local_infer_worker();

    async fn run(worker: &LocalInferWorker, prompt: &str) -> Vec<u8> {
        let workload_id = WorkloadId::new();
        let (channel, mut receiver) = generous_channel();
        let context = context_with(
            workload_id,
            AllocationContract::new(Duration::from_secs(120)),
            execution_parameters(prompt, "8"),
        );
        let report = worker
            .execute(context, channel)
            .await
            .expect("execute must complete successfully against a real model");
        assert_eq!(report.final_phase, ExecutionPhase::Completed);

        let mut bytes = Vec::new();
        while let Ok(event) = receiver.try_recv() {
            if let ExecutionEvent::OutputChunk(OutputChunk { data, .. }) = event {
                bytes.extend_from_slice(&data);
            }
        }
        bytes
    }

    let first = run(&worker, "Once upon a time,").await;
    let second = run(&worker, "Once upon a time,").await;

    assert_eq!(
        first, second,
        "greedy sampling (design.md D9) must be deterministic across runs"
    );
    assert!(!first.is_empty(), "the run must have produced some bytes");
}

#[tokio::test(flavor = "multi_thread")]
#[ignore]
async fn a_prompt_longer_than_the_context_window_is_rejected() {
    let _model = required_model_path();
    let worker = build_local_infer_worker();
    let workload_id = WorkloadId::new();
    let (channel, mut receiver) = generous_channel();
    // Far beyond any realistic context window: the widest GGUF models in
    // common use top out in the low hundreds of thousands of tokens.
    let context = context_with(
        workload_id,
        AllocationContract::new(Duration::from_secs(120)),
        execution_parameters(&"token ".repeat(300_000), "8"),
    );

    let report = worker
        .execute(context, channel)
        .await
        .expect("an over-long prompt still returns a report, not a WorkerError");
    assert_eq!(report.final_phase, ExecutionPhase::Failed);
    assert!(
        report.summary.contains("context window"),
        "the failure reason must name the context window, got: {}",
        report.summary
    );

    let mut events = Vec::new();
    while let Ok(event) = receiver.try_recv() {
        events.push(event);
    }
    assert!(
        events
            .iter()
            .all(|event| !matches!(event, ExecutionEvent::OutputChunk(_))),
        "an over-long prompt must be rejected before any token is produced"
    );
}
